from enum import Enum


class QCStatus(str, Enum):
    CLEAR = "CLEAR"
    CHANGE_CANDIDATE = "CHANGE_CANDIDATE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    NOT_VERIFIED = "NOT_VERIFIED"
